CREATE TYPE public.client_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.client_type
    OWNER TO cse340mlutz;

CREATE TABLE public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name CHARACTER VARYING NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make character varying NOT NULL,
	inv_model character varying NOT NULL,
	inv_year character(4) NOT NULL,
	inv_description text NOT NULL,
	inv_image character varying NOT NULL,
	inv_thumbnail character varying NOT NULL,
	inv_price numeric(9,0) NOT NULL,
	inv_miles integer NOT NULL,
	inv_colors character varying NOT NULL,
	classification_id integer NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between classification and inventory tables
ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

--Table structure for table `client`
CREATE TABLE IF NOT EXISTS public.client
(
	client_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	client_firstname character varying NOT NULL,
	client_lastname character varying NOT NULL,
	client_email character varying NOT NULL,
	client_password character varying NOT NULL,
	client_type client_type NOT NULL DEFAULT 'Client'::client_type,
	CONSTRAINT client_pkey PRIMARY KEY (client_id)
)

--Data for table `classification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
	('Sport'),
	('SUV'),
	('Truck'),
	('Sedan');
